name: ce

on:
  workflow_dispatch:
    inputs:
      codePath:
        type: string
      DOCKER_HUB_USR:
        type: string
      dockerfile:
        type: string
        default: RetPageOriginDockerfile
      registry:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --verbose

      - name: Check environment
        run: |
          node -v
          npm -v
          df -h
          printenv

      - name: Build project
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          npm run build --verbose

      - name: Debug build error
        if: failure()
        run: |
          ls -la
          cat some-log-file.log

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.DOCKER_HUB_USR }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Use codePath for multirepo
        if: ${{ inputs.codePath != '' }}
        run: |
          mkdir ./_repo
          cp -rf ./repo/${{ inputs.codePath }}/* ./_repo
          rm -rf ./repo
          mv ./_repo ./repo
          ls ./repo

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: repo/
          file: repo/${{ inputs.dockerfile }}
          tags: ${{ inputs.registry }}/${{ github.workflow }}:latest,${{ inputs.registry }}/${{ github.workflow }}:${{ github.run_number }}
          cache-from: type=registry,ref=${{ inputs.registry }}/${{ github.workflow }}:buildcache
          cache-to: type=registry,ref=${{ inputs.registry }}/${{ github.workflow }}:buildcache,mode=max
          push: true
